<?php
$submitMessage = "";


if (isset($_POST['submit']) && !empty($_POST['email'])) {
    
    $to = "lathan.ashton@pipint.com";
    

    $subject = "web info room - expired link accessed";

    // $parse = parse_url($_SERVER['HTTP_REFERER']);
    $url = $_SERVER['HTTP_REFERER'];
        
    $email = $_POST['email'];
    $name = $_POST['name'];
    $company = trim($_POST['company']);
    $message = trim($_POST['message']);
    
    // mail body
    $mailMessage = "Name: {$name} <br />";
    $mailMessage .= "Email: {$email} <br />";
    $mailMessage .=!empty($company) ? "Company: {$company} <br />" : "";
    $mailMessage .=!empty($message) ? "Message: {$message} <br />" : "";
    $mailMessage .=!empty($url) ? "URL: {$url} <br />" : "";

    // To send HTML mail, the Content-type header must be set
    $headers = 'MIME-Version: 1.0' . "\r\n";
    $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
    $headers .= 'X-Mailer: PHP/' . phpversion();

    // Additional headers
    $headers .= 'To: PIP Sales <sales@pipint.com>' . "\r\n";
    
    $headers .= 'From: PIP Sales <sales@pipint.com>' . "\r\n";
    
    //$headers .= 'Cc: birthdayarchive@example.com' . "\r\n";
    //$headers .= 'Bcc: birthdaycheck@example.com' . "\r\n";
    // Mail it

    if (!mail($to, $subject, $mailMessage, $headers)) {
        $submitMessage = '<span style="color:red;">Message could not be sent.</span><br>';
    } else {
        $headers = "";
        //email to submitter
        $to = $email;
        
        $subject = "Your request to access the expired link has been received";
        $submitterBody = "Hi,<br /> this email is to confirm that your request to access an expired link has been received and we will be touch shortly.<br /><br />";
       
        // To send HTML mail, the Content-type header must be set
        $headers = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
        $headers .= 'X-Mailer: PHP/' . phpversion();
        
        $mailMessageBody = $submitterBody.$mailMessage;
        // Additional headers
        $headers .= 'To: '.$name.' <'.$email.'>' . "\r\n";
        $headers .= 'From: PIP Sales <sales@pipint.com>' . "\r\n";
        
        if (!mail($to, $subject, $mailMessageBody, $headers)) {
            $submitMessage = '<span style="color:red;">Message could not be sent.</span><br>';
        }else{
            $submitMessage = '<span style="color:blue;">Message has been sent</span>';
        }
    }
}
?>



<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en-au"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en-au"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en-au"> <![endif]-->
<!--[if gt IE 8]><!-->
<html style="" class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients no-cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths" lang="en-au">
    <!--<![endif]-->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Partners in Performance</title>
        <meta name="keywords" content="Partners in Performance, PIP">
        <meta name="description" content="Welcome to Partners in Performance">
        <link rel="canonical" href="http://www.pipint.com/en">
        <!-- generated by seo_lite -->
        <meta name="author" content="August Pty Ltd">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="http://info.pipint.com/css/css-new.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="http://info.pipint.com/css/core-new.css">
		<script src="js/jquery-1.11.1.min.js"></script>
		<script src="js/jquery.validate.js"></script>

<!--[if lt IE 9]><script src="/common/dist/js/respond.min.js"></script><![endif]-->

    </head>
    <body class="home  loaded">
    <main>
        <header class="layout__header" role="banner">
            <div class="home__banner">
                <ul class="list-flat list-unstyled clearfix">
                    <li class="banner-1"></li>
                </ul>
            </div>
            <div class="home__header">
                <h2>We apologise but the information that you are trying to access has expired. Please complete your details below and we will reactivate the content and send you a confirmation e-mail.</h2>
                <h4><?php echo $submitMessage; ?></h4>
                <form method="post" id="landing-form" accept-charset="utf-8" action="http://info.pipint.com/index.php">
                    <div>
						<div class="form_content">
                            <label>Name:</label>
                            <input name="name" type="text" id="name" required>
                        </div>
                        <div class="form_content">
                            <label>E-mail:</label>
                            <input name="email" type="email" id="email" required>
                        </div>
                        <div class="form_content">
                            <label>Company:</label>
                            <input name="company" type="text" id="company">
                        </div>
                        <div class="form_content">
                            <label>Message:</label>
                            <textarea name="message" cols="" rows="" id="message"></textarea>
                        </div>
                        <div class="form_content">
                            <label>&nbsp;</label>
                            <input name="submit" type="submit" class="calltoaction" value="Submit">
                        </div>
                    </div>
                </form>
            </div>
            <footer class="layout__footer layout--margin">
                <div class="layout__footer__wrap">
                    <div class="layout__content clearfix">
                        <p class="layout__footer__trademark"><img src="img/logodark.png" width="361" height="24" alt=""/></p>
                        <p class="layout__footer__trademark">&nbsp;</p>
                        <p class="layout__footer__trademark">Partners in 
                            Performance ® is a registered trademark in Argentina, Australia, Brazil,
                            Chile, Colombia, Ireland, Mauritius, New Zealand, Russia and South 
                            Africa</p>
                    </div>
                </div>
            </footer>
        </header>
    </main>
</body>
</html>
<script>

$(document).ready(function() {
	// validate the form when it is submitted
		$("#landing-form").validate();
	});
</script>
<style>
input.error{
	background-color: #ffffd5;
    border: 2px solid red;
    color: red;
    margin: 0;
}
label.error{
	display:none !important;
}
</style>